In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("heart_attack_prediction_dataset.csv")
df

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [3]:
df.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0

In [4]:
print("The Shape of the dataset: " , df.shape)

The Shape of the dataset:  (8763, 26)

In [5]:
print("Summary Statistics: ",df.describe())

Summary Statistics:                 Age  Cholesterol   Heart Rate     Diabetes  Family History  \
count  8763.000000  8763.000000  8763.000000  8763.000000     8763.000000
mean     53.707977   259.877211    75.021682     0.652288        0.492982
std      21.249509    80.863276    20.550948     0.476271        0.499979
min      18.000000   120.000000    40.000000     0.000000        0.000000
25%      35.000000   192.000000    57.000000     0.000000        0.000000
50%      54.000000   259.000000    75.000000     1.000000        0.000000
75%      72.000000   330.000000    93.000000     1.000000        1.000000
max      90.000000   400.000000   110.000000     1.000000        1.000000

           Smoking      Obesity  Alcohol Consumption  Exercise Hours Per Week  \
count  8763.000000  8763.000000          8763.000000              8763.000000
mean      0.896839     0.501426             0.598083                10.014284
std       0.304186     0.500026             0.490313                 5.783745
min       0.000000     0.000000             0.000000                 0.002442
25%       1.000000     0.000000             0.000000                 4.981579
50%       1.000000     1.000000             1.000000                10.069559
75%       1.000000     1.000000             1.000000                15.050018
max       1.000000     1.000000             1.000000                19.998709

       Previous Heart Problems  Medication Use  Stress Level  \
count              8763.000000     8763.000000   8763.000000
mean                  0.495835        0.498345      5.469702
std                   0.500011        0.500026      2.859622
min                   0.000000        0.000000      1.000000
25%                   0.000000        0.000000      3.000000
50%                   0.000000        0.000000      5.000000
75%                   1.000000        1.000000      8.000000
max                   1.000000        1.000000     10.000000

       Sedentary Hours Per Day         Income          BMI  Triglycerides  \
count              8763.000000    8763.000000  8763.000000    8763.000000
mean                  5.993690  158263.181901    28.891446     417.677051
std                   3.466359   80575.190806     6.319181     223.748137
min                   0.001263   20062.000000    18.002337      30.000000
25%                   2.998794   88310.000000    23.422985     225.500000
50%                   5.933622  157866.000000    28.768999     417.000000
75%                   9.019124  227749.000000    34.324594     612.000000
max                  11.999313  299954.000000    39.997211     800.000000

       Physical Activity Days Per Week  Sleep Hours Per Day  Heart Attack Risk
count                      8763.000000          8763.000000        8763.000000
mean                          3.489672             7.023508           0.358211
std                           2.282687             1.988473           0.479502
min                           0.000000             4.000000           0.000000
25%                           2.000000             5.000000           0.000000
50%                           3.000000             7.000000           0.000000
75%                           5.000000             9.000000           1.000000
max                           7.000000            10.000000           1.000000

In [6]:
print("info about columns: ",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   object
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   object
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   int64
 7   Family History                   8763 non-null   int64
 8   Smoking                          8763 non-null   int64
 9   Obesity                          8763 non-null   int64
 10  Alcohol Consumption              8763 non-null   int64
 11  Exercise Hours Per Week          8763 non-null   float64
 12  Diet                             8763 non-null   object
 13  Previous Heart Problems          8763 non-null   int64
 14  Medication Use                   8763 non-null   int64
 15  Stress Level                     8763 non-null   int64
 16  Sedentary Hours Per Day          8763 non-null   float64
 17  Income                           8763 non-null   int64
 18  BMI                              8763 non-null   float64
 19  Triglycerides                    8763 non-null   int64
 20  Physical Activity Days Per Week  8763 non-null   int64
 21  Sleep Hours Per Day              8763 non-null   int64
 22  Country                          8763 non-null   object
 23  Continent                        8763 non-null   object
 24  Hemisphere                       8763 non-null   object
 25  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(16), object(7)
memory usage: 1.7+ MB
info about columns:  None

In [7]:
print("Missing values in each columns: ",df.isnull().sum())

Missing values in each columns:  Patient ID                         0
Age                                0
Sex                                0
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
Heart Attack Risk                  0
dtype: int64

In [8]:
categorical_cols= df.select_dtypes(include ="object").columns
print("categorical columns : ",categorical_cols)

categorical columns :  Index(['Patient ID', 'Sex', 'Blood Pressure', 'Diet', 'Country', 'Continent',
       'Hemisphere'],
      dtype='object')

In [9]:
df = df.drop('Patient ID',axis=1).copy()

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df['Sex'] = le.fit_transform(df['Sex'])

In [12]:
multi_cat = ['Blood Pressure', 'Diet', 'Country', 'Continent',
       'Hemisphere']
df = pd.get_dummies(df,columns = multi_cat,drop_first =True)

In [13]:
print("Encoded columns: ",df)

Encoded columns:        Age  Sex  Cholesterol  Heart Rate  Diabetes  Family History  Smoking  \
0      67    1          208          72         0               0        1
1      21    1          389          98         1               1        1
2      21    0          324          72         1               0        0
3      84    1          383          73         1               1        1
4      66    1          318          93         1               1        1
...   ...  ...          ...         ...       ...             ...      ...
8758   60    1          121          61         1               1        1
8759   28    0          120          73         1               0        0
8760   47    1          250         105         0               1        1
8761   36    1          178          60         1               0        1
8762   25    0          356          75         1               1        0

      Obesity  Alcohol Consumption  Exercise Hours Per Week  ...  \
0           0                    0                 4.168189  ...
1           1                    1                 1.813242  ...
2           0                    0                 2.078353  ...
3           0                    1                 9.828130  ...
4           1                    0                 5.804299  ...
...       ...                  ...                      ...  ...
8758        0                    1                 7.917342  ...
8759        1                    0                16.558426  ...
8760        1                    1                 3.148438  ...
8761        0                    0                 3.789950  ...
8762        0                    1                18.081748  ...

      Country_Thailand  Country_United Kingdom  Country_United States  \
0                False                   False                  False
1                False                   False                  False
2                False                   False                  False
3                False                   False                  False
4                 True                   False                  False
...                ...                     ...                    ...
8758              True                   False                  False
8759             False                   False                  False
8760             False                   False                  False
8761             False                   False                  False
8762             False                    True                  False

      Country_Vietnam  Continent_Asia  Continent_Australia  Continent_Europe  \
0               False           False                False             False
1               False           False                False             False
2               False           False                False              True
3               False           False                False             False
4               False            True                False             False
...               ...             ...                  ...               ...
8758            False            True                False             False
8759            False           False                False             False
8760            False           False                False             False
8761            False           False                False             False
8762            False           False                False              True

      Continent_North America  Continent_South America  \
0                       False                     True
1                        True                    False
2                       False                    False
3                        True                    False
4                       False                    False
...                       ...                      ...
8758                    False                    False
8759                     True                    False
8760                    False                     True
8761                    False                     True
8762                    False                    False

      Hemisphere_Southern Hemisphere
0                               True
1                              False
2                              False
3                              False
4                              False
...                              ...
8758                           False
8759                           False
8760                            True
8761                            True
8762                           False

[8763 rows x 3961 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
numerical_cols = ['Age', 'Cholesterol', 'Heart Rate', 
                  'Exercise Hours Per Week','BMI']

In [17]:
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [18]:
print(df.head())

        Age  Sex  Cholesterol  Heart Rate  Diabetes  Family History  Smoking  \
0  0.625557    1    -0.641579   -0.147042         0               0        1
1 -1.539322    1     1.596895    1.118179         1               1        1
2 -1.539322    0     0.793023   -0.147042         1               0        0
3  1.425621    1     1.522691   -0.098380         1               1        1
4  0.578495    1     0.718820    0.874867         1               1        1

   Obesity  Alcohol Consumption  Exercise Hours Per Week  ...  \
0        0                    0                -1.010838  ...
1        1                    1                -1.418027  ...
2        0                    0                -1.372188  ...
3        0                    1                -0.032188  ...
4        1                    0                -0.727941  ...

   Country_Thailand  Country_United Kingdom  Country_United States  \
0             False                   False                  False
1             False                   False                  False
2             False                   False                  False
3             False                   False                  False
4              True                   False                  False

   Country_Vietnam  Continent_Asia  Continent_Australia  Continent_Europe  \
0            False           False                False             False
1            False           False                False             False
2            False           False                False              True
3            False           False                False             False
4            False            True                False             False

   Continent_North America  Continent_South America  \
0                    False                     True
1                     True                    False
2                    False                    False
3                     True                    False
4                    False                    False

   Hemisphere_Southern Hemisphere
0                            True
1                           False
2                           False
3                           False
4                           False

[5 rows x 3961 columns]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X = df.drop("Heart Attack Risk",axis=1)
y = df["Heart Attack Risk"]

In [50]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.10,random_state=42)

In [51]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [52]:
print("Training State: ",X_train.shape)
print("Test Set: ",X_test.shape)

Training State:  (7886, 3960)
Test Set:  (877, 3960)

In [53]:
print("y_train shape: ",y_train.shape)
print("y_test shape: ",y_test.shape)

y_train shape:  (7886,)
y_test shape:  (877,)

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [55]:
parameters = {'C' : [0.01,0.1,1,10],
              'penalty' : ['l2'],
              'solver' : ['lbfgs','liblinear']}

In [56]:
logic = LogisticRegression(max_iter =1000,random_state=42)
grid_search = GridSearchCV(logic,parameters,cv=5,scoring='accuracy')

In [57]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000, random_state=42),
             param_grid={'C': [0.01, 0.1, 1, 10], 'penalty': ['l2'],
                         'solver': ['lbfgs', 'liblinear']},
             scoring='accuracy')

In [58]:
print("Best Parameters: ",grid_search.best_params_)
best_model = grid_search.best_estimator_

Best Parameters:  {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}

In [59]:
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:,-1]

In [60]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,classification_report,confusion_matrix

In [61]:
print("Accuracy of the model: " ,accuracy_score(y_test,y_pred))

Accuracy of the model:  0.5792474344355758

In [62]:
print("Precision: ",precision_score(y_test,y_pred))

Precision:  0.3925619834710744

In [63]:
print("Recall : ",recall_score(y_test,y_pred))

Recall :  0.2996845425867508

In [64]:
print("F1 score: ",f1_score(y_test,y_pred))

F1 score:  0.33989266547406083

In [65]:
print("ROC-AUC: ",roc_auc_score(y_test,y_pred))

ROC-AUC:  0.5185922712933754

In [66]:
print("Classification Report: ",classification_report(y_test,y_pred))

Classification Report:                precision    recall  f1-score   support

           0       0.65      0.74      0.69       560
           1       0.39      0.30      0.34       317

    accuracy                           0.58       877
   macro avg       0.52      0.52      0.52       877
weighted avg       0.56      0.58      0.56       877

In [67]:
print("Confusion matrix: ",confusion_matrix(y_test,y_pred))

Confusion matrix:  [[413 147]
 [222  95]]