In [3]:
import pandas as pd

In [5]:
data = { 'Name' : ['Alice' , 'Bob' , 'Charlie' , 'David'],
        'Age' : [25, 30, 35, 40] ,
        'City' : ['New York' , 'Los Angeles' , 'Chicago' , 'Houston' ]
       }

In [7]:
df = pd.DataFrame(data)

In [9]:
selected_column = df[['Name' , 'City' ]]

In [11]:
selected_column

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [13]:
selected_rows = df.iloc[1:3]

In [15]:
selected_rows

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago